#!/bin/bash
# deployment/deploy-azure.sh
# Script to deploy the ticket classifier infrastructure to Azure

set -e  # Exit on error

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Functions
print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

print_error() {
    echo -e "${RED}✗ $1${NC}"
}

print_info() {
    echo -e "${YELLOW}ℹ $1${NC}"
}

# Check prerequisites
check_prerequisites() {
    print_info "Checking prerequisites..."
    
    # Check Azure CLI
    if ! command -v az &> /dev/null; then
        print_error "Azure CLI is not installed. Install from: https://docs.microsoft.com/cli/azure/install-azure-cli"
        exit 1
    fi
    print_success "Azure CLI found"
    
    # Check kubectl (for AKS deployments)
    if ! command -v kubectl &> /dev/null; then
        print_info "kubectl not found. Installing..."
        az aks install-cli
    fi
    print_success "kubectl found"
    
    # Check logged in to Azure
    if ! az account show &> /dev/null; then
        print_error "Not logged in to Azure. Run: az login"
        exit 1
    fi
    print_success "Logged in to Azure"
}

# Parse arguments
ENVIRONMENT=${1:-dev}
LOCATION=${2:-eastus}
APP_NAME=${3:-ticket-classifier}

if [[ ! "$ENVIRONMENT" =~ ^(dev|staging|prod)$ ]]; then
    print_error "Invalid environment. Must be: dev, staging, or prod"
    exit 1
fi

print_info "Deploying to environment: $ENVIRONMENT"
print_info "Location: $LOCATION"
print_info "Application: $APP_NAME"

# Variables
RESOURCE_GROUP="rg-${APP_NAME}-${ENVIRONMENT}"
DEPLOYMENT_NAME="deploy-${APP_NAME}-$(date +%Y%m%d-%H%M%S)"

# Check prerequisites
check_prerequisites

# Get subscription info
SUBSCRIPTION_ID=$(az account show --query id -o tsv)
SUBSCRIPTION_NAME=$(az account show --query name -o tsv)
print_info "Subscription: $SUBSCRIPTION_NAME ($SUBSCRIPTION_ID)"

# Confirm deployment
read -p "Deploy to $ENVIRONMENT environment in $LOCATION? (yes/no): " CONFIRM
if [[ "$CONFIRM" != "yes" ]]; then
    print_error "Deployment cancelled"
    exit 1
fi

# Create resource group
print_info "Creating resource group: $RESOURCE_GROUP..."
az group create \
    --name "$RESOURCE_GROUP" \
    --location "$LOCATION" \
    --tags Environment="$ENVIRONMENT" Application="$APP_NAME" \
    > /dev/null

print_success "Resource group created"

# Deploy infrastructure
print_info "Deploying infrastructure (this may take 10-15 minutes)..."
DEPLOYMENT_OUTPUT=$(az deployment group create \
    --resource-group "$RESOURCE_GROUP" \
    --name "$DEPLOYMENT_NAME" \
    --template-file deployment/azure-deploy.yml \
    --parameters \
        environment="$ENVIRONMENT" \
        applicationName="$APP_NAME" \
        location="$LOCATION" \
    --query 'properties.outputs' \
    -o json)

print_success "Infrastructure deployed successfully"

# Extract outputs
ACR_LOGIN_SERVER=$(echo "$DEPLOYMENT_OUTPUT" | jq -r '.acrLoginServer.value')
COSMOS_ENDPOINT=$(echo "$DEPLOYMENT_OUTPUT" | jq -r '.cosmosDbEndpoint.value')
OPENAI_ENDPOINT=$(echo "$DEPLOYMENT_OUTPUT" | jq -r '.openAIEndpoint.value')
APP_INSIGHTS_CONN=$(echo "$DEPLOYMENT_OUTPUT" | jq -r '.appInsightsConnectionString.value')
KEY_VAULT_URI=$(echo "$DEPLOYMENT_OUTPUT" | jq -r '.keyVaultUri.value')

echo ""
print_success "Deployment completed!"
echo ""
echo "=== Deployment Information ==="
echo "Resource Group: $RESOURCE_GROUP"
echo "ACR Login Server: $ACR_LOGIN_SERVER"
echo "Cosmos DB Endpoint: $COSMOS_ENDPOINT"
echo "OpenAI Endpoint: $OPENAI_ENDPOINT"
echo "Key Vault URI: $KEY_VAULT_URI"

# Environment-specific outputs
if [[ "$ENVIRONMENT" == "dev" ]]; then
    ACI_ENDPOINT=$(echo "$DEPLOYMENT_OUTPUT" | jq -r '.aciEndpoint.value')
    echo "ACI Endpoint: $ACI_ENDPOINT"
    echo ""
    print_info "Your application will be available at: $ACI_ENDPOINT"
else
    AKS_CLUSTER=$(echo "$DEPLOYMENT_OUTPUT" | jq -r '.aksClusterName.value')
    AKS_FQDN=$(echo "$DEPLOYMENT_OUTPUT" | jq -r '.aksFqdn.value')
    echo "AKS Cluster: $AKS_CLUSTER"
    echo "AKS FQDN: $AKS_FQDN"
    echo ""
    
    # Get AKS credentials
    print_info "Getting AKS credentials..."
    az aks get-credentials \
        --resource-group "$RESOURCE_GROUP" \
        --name "$AKS_CLUSTER" \
        --overwrite-existing
    print_success "AKS credentials configured"
fi

# Save outputs to file
OUTPUT_FILE="deployment/.env.$ENVIRONMENT"
cat > "$OUTPUT_FILE" <<EOF
# Generated by deploy-azure.sh on $(date)
# Environment: $ENVIRONMENT

AZURE_SUBSCRIPTION_ID=$SUBSCRIPTION_ID
AZURE_RESOURCE_GROUP=$RESOURCE_GROUP
ACR_LOGIN_SERVER=$ACR_LOGIN_SERVER
COSMOS_ENDPOINT=$COSMOS_ENDPOINT
OPENAI_ENDPOINT=$OPENAI_ENDPOINT
APP_INSIGHTS_CONNECTION_STRING=$APP_INSIGHTS_CONN
KEY_VAULT_URI=$KEY_VAULT_URI
EOF

print_success "Configuration saved to: $OUTPUT_FILE"

# Next steps
echo ""
echo "=== Next Steps ==="
echo "1. Build and push your Docker image:"
echo "   docker build -t $ACR_LOGIN_SERVER/$APP_NAME:latest ."
echo "   az acr login --name ${ACR_LOGIN_SERVER%%.*}"
echo "   docker push $ACR_LOGIN_SERVER/$APP_NAME:latest"
echo ""

if [[ "$ENVIRONMENT" != "dev" ]]; then
    echo "2. Deploy to Kubernetes:"
    echo "   kubectl apply -f deployment/k8s/"
    echo ""
fi

echo "3. Test the deployment:"
if [[ "$ENVIRONMENT" == "dev" ]]; then
    echo "   curl $ACI_ENDPOINT/health"
else
    echo "   kubectl get pods -n production"
fi

echo ""
print_success "Deployment script completed!"